server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: servizio-studenti
          uri: http://servizio-studenti:8081
          predicates:
            - Path=/api/studenti/**
          filters:
            - StripPrefix=0

        - id: servizio-corsi
          uri: http://servizio-corsi:8083
          predicates:
            - Path=/api/corsi/**
          filters:
            - StripPrefix=0

        - id: servizio-iscrizioni
          uri: http://servizio-iscrizioni:8082
          predicates:
            - Path=/api/iscrizioni/**
          filters:
            - StripPrefix=0

        - id: servizio-voti
          uri: http://servizio-voti:8084
          predicates:
            - Path=/api/voti/**
          filters:
            - StripPrefix=0

        - id: servizio-rapporti
          uri: http://servizio-rapporti:8085
          predicates:
            - Path=/api/rapporti/**
          filters:
            - StripPrefix=0

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders: "*"