server:
  port: 8085

spring:
  application:
    name: servizio-rapporti

# Nessun database — il Servizio Rapporti chiama gli altri via Feign e aggrega

# URL di tutti i servizi
servizi:
  studenti:
    url: http://localhost:8081
  corsi:
    url: http://localhost:8083
  iscrizioni:
    url: http://localhost:8082
  voti:
    url: http://localhost:8084

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
